######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 20 17:47:04 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += scan.cpp
